spring:
  application:
    name: e-commerce
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 3600

logging:
  level:
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([${spring.application.name}]){green} %clr(%logger{36}){cyan} - %msg%n"
